# ===============================================================
# IoT Batch Ingestion System
# ---------------------------------------------------------------
# This Docker Compose file orchestrates three key services:
# 1. MongoDB: Database for storing IoT sensor data.
# 2. Mongo Express: Web-based interface to explore MongoDB data.
# 3. App: Python-based ETL container for data cleaning and ingestion.
# The setup ensures full reproducibility and can be deployed locally
# or in the cloud with minimal changes.
# ===============================================================

services:
  # -------------------------------------------------------------
  # 1. MongoDB Database Service
  # -------------------------------------------------------------
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # Expose database port for local connections
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: iot
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # Auto-run index creation script
      - mongo_data:/data/db                 # Persistent data storage

  # -------------------------------------------------------------
  # 2. Mongo Express (Database Visualization)
  # -------------------------------------------------------------
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"  # Accessible via http://localhost:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  # -------------------------------------------------------------
  # 3. Python Application (ETL & Batch Ingestion)
  # -------------------------------------------------------------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-batch-app
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/?authSource=admin
      MONGODB_DB: iot
      MONGODB_COLLECTION: measurements
      CHUNK_SIZE: 50000
    volumes:
      - ./data:/app/data        # Mount dataset folder
      - ./app:/app              # Mount app scripts
    command: >
      python -u ingest.py
      --file /app/data/cleaned_IoT_data.csv
      --chunk-size 50000
    # Optional: Uncomment for continuous log output
    # tty: true

# ---------------------------------------------------------------
# Named volume for MongoDB data persistence
# ---------------------------------------------------------------
volumes:
  mongo_data:
